services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NUXT_PUBLIC_API_BASE_URL=http://localhost:8000/api
      - NUXT_PUBLIC_GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=restaurant_finder
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - APP_KEY=base64:6xYPpYOKzLTVBXpLKL8Jg1J9mOFkPZBpLmGXqVgKjJ8=
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  database:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=restaurant_finder
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped

volumes:
  mysql_data: 