// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/11/2025, 8:55:50 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/ukrit.p/Desktop/TEST/resturant-finder-nuxt-laravel/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ukrit.p/Desktop/TEST/resturant-finder-nuxt-laravel/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ukrit.p/Desktop/TEST/resturant-finder-nuxt-laravel/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ukrit.p/Desktop/TEST/resturant-finder-nuxt-laravel/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ukrit.p/Desktop/TEST/resturant-finder-nuxt-laravel/frontend/plugins/**/*.{js,ts,mjs}","/Users/ukrit.p/Desktop/TEST/resturant-finder-nuxt-laravel/frontend/composables/**/*.{js,ts,mjs}","/Users/ukrit.p/Desktop/TEST/resturant-finder-nuxt-laravel/frontend/utils/**/*.{js,ts,mjs}","/Users/ukrit.p/Desktop/TEST/resturant-finder-nuxt-laravel/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ukrit.p/Desktop/TEST/resturant-finder-nuxt-laravel/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/ukrit.p/Desktop/TEST/resturant-finder-nuxt-laravel/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/ukrit.p/Desktop/TEST/resturant-finder-nuxt-laravel/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;