// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/12/2025, 9:14:09 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/ukrit.p/Desktop/TEST/resturant-finder-nuxt-laravel/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ukrit.p/Desktop/TEST/resturant-finder-nuxt-laravel/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ukrit.p/Desktop/TEST/resturant-finder-nuxt-laravel/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ukrit.p/Desktop/TEST/resturant-finder-nuxt-laravel/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ukrit.p/Desktop/TEST/resturant-finder-nuxt-laravel/plugins/**/*.{js,ts,mjs}","/Users/ukrit.p/Desktop/TEST/resturant-finder-nuxt-laravel/composables/**/*.{js,ts,mjs}","/Users/ukrit.p/Desktop/TEST/resturant-finder-nuxt-laravel/utils/**/*.{js,ts,mjs}","/Users/ukrit.p/Desktop/TEST/resturant-finder-nuxt-laravel/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ukrit.p/Desktop/TEST/resturant-finder-nuxt-laravel/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/ukrit.p/Desktop/TEST/resturant-finder-nuxt-laravel/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/ukrit.p/Desktop/TEST/resturant-finder-nuxt-laravel/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;